### ISSUE TITLE
Throws exception when deserialize large string and exists escape character

### ISSUE THREAD

**Issue by neuecc** [neuecc/Utf8Json#39]
This is a critical bug.

**Comment by neuecc** [comment]
I've released 1.3.4, it includes this fix.

**Comment by t-matuda** [comment]
Hi,
I think this bug still remains.
ArgumentException is thrown when calling Deserialize method in the following snippet.
```
Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Utf8Json.JsonReader.ReadStringSegmentCore(Byte[]& resultBytes, Int32& resultOffset, Int32& resultLength)
   at Utf8Json.JsonReader.ReadString()
   at Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Utf8JsonTest.Program.Main(String[] args) in Program.cs:line 14
```

``` csharp
using Utf8Json;

namespace Utf8JsonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var origstr = new string('a', 99999);
            var str = "\"" + origstr + "\"";

            var serialized = JsonSerializer.Serialize(str);
            var deserialized = JsonSerializer.Deserialize<string>(serialized);
        }
    }
}

```

**Comment by neuecc** [comment]
Thanks!
I can reproduced and fixed it!
I'll update release soon.

**Comment by neuecc** [comment]
I've upload ver 1.3.5.

**Comment by t-matuda** [comment]
Thank you for changing code, but another exception has occurred when I tried to deserialize longer string such as  **999999**.
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Utf8Json.JsonReader.ReadStringSegmentCore(Byte[]& resultBytes, Int32& resultOffset, Int32& resultLeng
th)
   at Utf8Json.JsonReader.ReadString()
   at Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
```

**Comment by neuecc** [comment]
@t-matuda 
Could you provide full code to reproduce issue?
My simple test code can't reproduce it.
https://github.com/neuecc/Utf8Json/commit/cb1fa30e6d3bfbae4f2ad86cb1cccdec55f38b8a

**Comment by t-matuda** [comment]
I just changed lengh of original string.
```csharp
using Utf8Json;

namespace Utf8JsonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            //It's ok.
            //var origstr = new string('a', 99999);
            var origstr = new string('a', 999999);
            var str = "\"" + origstr + "\"";

            var serialized = JsonSerializer.Serialize(str);
            var deserialized = JsonSerializer.Deserialize<string>(serialized);
        }
    }
}
```

**Comment by neuecc** [comment]
Thank you, https://github.com/neuecc/Utf8Json/commit/3e7c6c4af5fd662d68975bcabc3f66c89d4bf45c commit fixed this issue.
I'll add more test and release soon.

**Comment by neuecc** [comment]
I've upload ver 1.3.6.

**Comment by t-matuda** [comment]
Thank you!
It works fine.
