### ISSUE TITLE
DateTime/DateTimeOffset serialization problems

### ISSUE THREAD

**Issue by Tornhoof** [neuecc/Utf8Json#5]
There are currently multiple problems with DT/DTO serialization/deserialization

## Description:
Compare ToString(...) functionality of DT/DTO with serialized/deserialized output.
ToString format is {0:yyyy-MM-ddTHH:mm:ss.fffffffK} (https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
My current TZ is GMT+2 (Berlin time)

## Problems
1. Loss in precision, any sub-ms precision is lost after the roundtrip, you probably should increase the precision to full precision to allow roundtrips and be compatible
2. Wrong TZ in DateTime.Now output (not sure where the +1 comes from)

## Example output:
DateTime.UtcNow
Reference: 2017-09-27T11:20:15.5785405Z
Output: "2017-09-27T11:20:15.578**5405**Z" vs "2017-09-27T11:20:15.578**0000**Z"
DateTimeOffset.UtcNow
Reference: 2017-09-27T11:20:15.6450980+00:00
Output: "2017-09-27T11:20:15.6450980+00:00" vs "2017-09-27T11:20:15.6450000+00:00"
DateTime.Now
Reference: 2017-09-27T13:20:15.6541047+**02:00**
Output: "2017-09-27T13:20:15.6541047+**01:00**" vs "2017-09-27T14:20:15.6540000+**01:00**"
DateTimeOffset.Now
Reference: 2017-09-27T13:20:15.6581082+02:00
Output: "2017-09-27T13:20:15.6581082+02:00" vs "2017-09-27T13:20:15.6580000+02:00"

##  Repro:
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DateTimePrecision
{
    class Program
    {
        static void Main(string[] args)
        {
            TestDTUtcNow();
            TestDTOUtcNow();
            TestDTNow();
            TestDTONow();
        }

        static void TestDTUtcNow()
        {
            Console.WriteLine("DateTime.UtcNow");
            var dto = DateTime.UtcNow;
            var serialized = Utf8Json.JsonSerializer.ToJsonString(dto);
            var deSerialized = Utf8Json.JsonSerializer.Deserialize<DateTime>(serialized);
            var serialized2 = Utf8Json.JsonSerializer.ToJsonString(deSerialized);
            if (serialized2 != serialized)
            {
                Console.WriteLine("Reference: {0:yyyy-MM-ddTHH:mm:ss.fffffffK}", dto);
                Console.WriteLine("Output: {0} vs {1}", serialized, serialized2);
            }
        }


        static void TestDTOUtcNow()
        {
            Console.WriteLine("DateTimeOffset.UtcNow");
            var dto = DateTimeOffset.UtcNow;
            var serialized = Utf8Json.JsonSerializer.ToJsonString(dto);
            var deSerialized = Utf8Json.JsonSerializer.Deserialize<DateTimeOffset>(serialized);
            var serialized2 = Utf8Json.JsonSerializer.ToJsonString(deSerialized);
            if (serialized2 != serialized)
            {
                Console.WriteLine("Reference: {0:yyyy-MM-ddTHH:mm:ss.fffffffK}", dto);
                Console.WriteLine("Output: {0} vs {1}", serialized, serialized2);
            }
        }

        static void TestDTNow()
        {
            Console.WriteLine("DateTime.Now");
            var dto = DateTime.Now;
            var serialized = Utf8Json.JsonSerializer.ToJsonString(dto);
            var deSerialized = Utf8Json.JsonSerializer.Deserialize<DateTime>(serialized);
            var serialized2 = Utf8Json.JsonSerializer.ToJsonString(deSerialized);
            if (serialized2 != serialized)
            {
                Console.WriteLine("Reference: {0:yyyy-MM-ddTHH:mm:ss.fffffffK}", dto);
                Console.WriteLine("Output: {0} vs {1}", serialized, serialized2);
            }
        }


        static void TestDTONow()
        {
            Console.WriteLine("DateTimeOffset.Now");
            var dto = DateTimeOffset.Now;
            var serialized = Utf8Json.JsonSerializer.ToJsonString(dto);
            var deSerialized = Utf8Json.JsonSerializer.Deserialize<DateTimeOffset>(serialized);
            var serialized2 = Utf8Json.JsonSerializer.ToJsonString(deSerialized);
            if (serialized2 != serialized)
            {
                Console.WriteLine("Reference: {0:yyyy-MM-ddTHH:mm:ss.fffffffK}", dto);
                Console.WriteLine("Output: {0} vs {1}", serialized, serialized2);
            }
        }
    }
}

```

**Comment by neuecc** [comment]
sorry, ISO8601 formatters does not work correctly.
I've fully refactored and add more unit tests.

**Comment by neuecc** [comment]
I've released 1.0.2, thank you very much for report many issues!

**Comment by Tornhoof** [comment]
With my Testprogram from above the output for DateTime.Now is still wrong regarding the Timezone information:
DateTime.Now
Reference: 2017-09-27T22:44:08.4946355+02:00
Output: "2017-09-27T22:44:08.4946355+01:00" vs "2017-09-27T23:44:08.4946355+01:00"

The first serialized value has the proper time and the wrong TZ, the value after the roundtrip has the wrong time and the wrong TZ.

The precision is fixed though.

**Comment by neuecc** [comment]
TZ problem is about DST?
https://stackoverflow.com/questions/10019267/is-there-a-generic-timezoneinfo-for-central-europe

actually currently using `TimeZoneInfo.Local.BaseUtcOffset`.
https://github.com/neuecc/Utf8Json/blob/72d60e6406aaa951bc7bec319d7e268130301f4c/src/Utf8Json/Formatters/DateTimeFormatter.cs#L168

I'll try to Jon Skeet's answer.

**Comment by neuecc** [comment]
I've released `v1.0.3`.

**Comment by Tornhoof** [comment]
With 1.0.3 my test works. I'm closing this.
